/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,jsx}",
    "./components/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error": "#690005",
        "surface-container": "#191f2e",
        "inverse-on-surface": "#2a3040",
        "surface-container-lowest": "#080e1c",
        "on-tertiary": "#213147",
        "on-secondary-fixed-variant": "#3c475d",
        "inverse-surface": "#dde2f6",
        "tertiary-fixed-dim": "#b7c7e4",
        "on-tertiary-container": "#36455c",
        error: "#ffb4ab",
        "on-primary-fixed-variant": "#005142",
        "on-tertiary-fixed": "#0b1c31",
        "on-secondary-container": "#adb8d3",
        "surface-container-low": "#151b2a",
        "on-surface-variant": "#bacac3",
        "on-primary": "#00382d",
        "on-primary-container": "#004e40",
        "on-surface": "#dde2f6",
        "primary-fixed-dim": "#38debb",
        "tertiary-container": "#a3b3cf",
        "surface-container-highest": "#2f3444",
        "surface-container-high": "#242a39",
        "tertiary-fixed": "#d4e3ff",
        "error-container": "#93000a",
        "on-primary-fixed": "#002019",
        "secondary-fixed": "#d7e3fe",
        "secondary-fixed-dim": "#bbc7e2",
        "secondary-container": "#3e4960",
        background: "#0d1321",
        secondary: "#bbc7e2",
        "on-secondary": "#253146",
        surface: "#0d1321",
        "surface-bright": "#333949",
        "inverse-primary": "#006b58",
        "outline-variant": "#3c4a45",
        "on-background": "#dde2f6",
        "surface-tint": "#38debb",
        outline: "#85948e",
        primary: "#44e5c2",
        "surface-variant": "#2f3444",
        "primary-container": "#00c9a7",
        "on-secondary-fixed": "#101c30",
        tertiary: "#becfeb",
        "primary-fixed": "#5ffbd6",
        "on-tertiary-fixed-variant": "#38485f",
        "surface-dim": "#0d1321",
        "on-error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "container-max": "1200px",
        "section-padding": "120px",
        gutter: "32px",
        unit: "8px",
        "margin-mobile": "20px",
      },
      maxWidth: {
        "container-max": "1200px",
      },
      fontFamily: {
        "headline-sm": ["var(--font-montserrat)", "Montserrat", "sans-serif"],
        button: ["var(--font-montserrat)", "Montserrat", "sans-serif"],
        "body-lg": ["var(--font-montserrat)", "Montserrat", "sans-serif"],
        "display-lg": ["var(--font-playfair)", "Playfair Display", "serif"],
        "headline-md": ["var(--font-playfair)", "Playfair Display", "serif"],
        "display-lg-mobile": ["var(--font-playfair)", "Playfair Display", "serif"],
        "body-md": ["var(--font-montserrat)", "Montserrat", "sans-serif"],
        "label-caps": ["var(--font-montserrat)", "Montserrat", "sans-serif"],
      },
      fontSize: {
        "headline-sm": ["24px", { lineHeight: "1.4", letterSpacing: "0.02em", fontWeight: "600" }],
        button: ["14px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
